### ISSUE TITLE
3 mobiele applicaties controleren

### ISSUE THREAD

**Issue by MisterQuack** [XR-Solutions/watson-mr#21]
-polycam (.gltf)
-Realityscan
-Kiri Engine

Gaat met name om waarin het model geëxporteerd wordt.

**Comment by c9d5e1** [comment]
polycam:
free gltf
paid obj, fbx, dae, stl usdz

**Comment by c9d5e1** [comment]
realityscan
original format .fbx
converted usdz gltf glb

**Comment by c9d5e1** [comment]
kiri
fbx

**Comment by c9d5e1** [comment]
ze zijn allemaal limited in some way tenzei je betaald, maar realiutyscan upload naar sketchfab
